repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.2
  hooks:
    # Run the linter.
    - id: ruff-check
      files: src/rpcclient
    # Run the formatter.
    - id: ruff-format
      files: src/rpcclient
